apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akamai-gtm-metrics-exporter.fullname" . }}-config
  labels:
    {{- include "akamai-gtm-metrics-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    summary_window: {{ .Values.config.summaryWindow | quote }}
    prefill_window: {{ .Values.config.prefillWindow | quote }}
    timestamp_label: {{ .Values.config.timestampLabel }}
    traffic_timestamp: {{ .Values.config.trafficTimestamp }}
    domains:
    {{- if .Values.config.domains }}
      {{- toYaml .Values.config.domains | nindent 6 }}
    {{- else }}
      []
    {{- end }}