{{- if .Values.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akamai-gtm-metrics-exporter.credentialsSecretName" . }}
  labels:
    {{- include "akamai-gtm-metrics-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.credentials.existingSecretKeys.host }}: {{ required "credentials.secretData.host is required when credentials.create=true" .Values.credentials.secretData.host | quote }}
  {{ .Values.credentials.existingSecretKeys.clientToken }}: {{ required "credentials.secretData.clientToken is required when credentials.create=true" .Values.credentials.secretData.clientToken | quote }}
  {{ .Values.credentials.existingSecretKeys.clientSecret }}: {{ required "credentials.secretData.clientSecret is required when credentials.create=true" .Values.credentials.secretData.clientSecret | quote }}
  {{ .Values.credentials.existingSecretKeys.accessToken }}: {{ required "credentials.secretData.accessToken is required when credentials.create=true" .Values.credentials.secretData.accessToken | quote }}
{{- end }}
