{{- if .Values.edgegridSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.edgegridSecret.name }}
  labels:
    {{- include "akamai-gtm-metrics-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.edgegridSecret.hostRef }}: {{ required "edgegridSecret.host is required when edgegridSecret.create=true" .Values.edgegridSecret.host | quote }}
  {{ .Values.edgegridSecret.clientTokenRef }}: {{ required "edgegridSecret.clientToken is required when edgegridSecret.create=true" .Values.edgegridSecret.clientToken | quote }}
  {{ .Values.edgegridSecret.clientSecretRef }}: {{ required "edgegridSecret.clientSecret is required when edgegridSecret.create=true" .Values.edgegridSecret.clientSecret | quote }}
  {{ .Values.edgegridSecret.accessTokenRef }}: {{ required "edgegridSecret.accessToken is required when edgegridSecret.create=true" .Values.edgegridSecret.accessToken | quote }}
{{- end }}
